# this secret to allow ArgoCD  Image updater to access to private docker repo
apiVersion: v1
kind: Secret
metadata:
  name: updater-to-private-dockerhub2
  namespace: argocd
type: Opaque
stringData:
  token: <dockerUser:dockerPassword>
