apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: heml-myrepo
  namespace: argocd # the same where the Ardo CD is placed
  annotations:
    argocd-image-updater.argoproj.io/image-list: docker.io/solkoff/nginx:~0.4 # to watch this DockerRepo, and upgrade it the patch version increases
    argocd-image-updater.argoproj.io/write-back-method: git # it creates a git commit
  finalizers:
    - resources-finalizer.argocd.argoproj.io # will delete ARGOCD app and K8s app at the same time
spec:
  project: default 

  source:
    repoURL: git@github.com:solkoff/argocd-anton-application-private-with-updater.git # Helm repo
    targetRevision: main
    path: myapp-chart
    helm:
      version: v3
      releaseName: myapp-chart
      passCredentials: true # private repo + we added a new 
      parameters: # overwrite default variables
        - name: replicaCount
          value: "1"
        - name: image.repositary
          value: solkoff/nginx
        - name: image.tag
          value: 0.1.5
  destination: 
    server: https://kubernetes.default.svc #since the service is inside the cluster


  syncPolicy: # argocd will create a namespace if needed
    syncOptions:
    - CreateNamespace=true
    - Validate=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true

    automated:
      selfHeal: true
      prune: true