# secret with a private ssh key that corresponds to the private repo
apiVersion: v1
kind: Secret
metadata:
  name: private-git-repo3
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: git@github.com:solkoff/argocd-anton-application-private-with-updater.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    ...
    -----END OPENSSH PRIVATE KEY-----
  insecure: "false"
  enableLfs: "true"